# ====================================================================
# Runtime mode are only one
# ====================================================================
info:
  name: study
  contact: 学习
server:
  port: 8761
  tomcat:
    max-threads: 600